#!/bin/bash

set -ex

# This shouldn't be in the Dockerfile or containers built from the same image
# will have the same credentials.
if [ ! -e "$HOME/.bitcoin/bitcoin.conf" ]; then
    mkdir -p $HOME/.bitcoin

    echo "Creating bitcoin.conf"

    cat <<EOF > $HOME/.bitcoin/bitcoin.conf
disablewallet=0
rpcallowip=0.0.0.0
printtoconsole=1
rpcuser=rpcuser
rpcpassword=rpcpassword
EOF

fi

cat $HOME/.bitcoin/bitcoin.conf

echo "Initialization completed successfully"
